image: golang:1.10

stages:
- test
- build
- docker

before_script:
- go get -u github.com/golang/dep/cmd/dep
- mkdir -p $GOPATH/src
- cd $GOPATH/src
- ln -s $CI_PROJECT_DIR
- cd $CI_PROJECT_NAME
- dep ensure

test:
  stage: test
  script:
  - go test

build:
  stage: build
  script:
  - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .

docker:
  stage: docker
  services:
  - docker:dind
  script:
  - docker build -t registry.gitlab.com/lasayter/hashtag-connector:${CI_COMMIT_SHA:0:8} -f Dockerfile.scratch .
  - docker login registry.gitlab.com -u ${REGISTRY_LOGIN} -p ${REGISTRY_PASSWORD}
  - docker push registry.gitlab.com/lasayter/hashtag-connector:${CI_COMMIT_SHA:0:8}